import os

CELL_SIZE = 50
GRID_WIDTH = 100
GRID_HEIGHT = 100
GRID_WIDTH_PIX = GRID_WIDTH * CELL_SIZE
GRID_HEIGHT_PIX = GRID_HEIGHT * CELL_SIZE

# In cells
SCREEN_WIDTH = 30
SCREEN_WIDTH_PIX = SCREEN_WIDTH * CELL_SIZE
SCREEN_HEIGHT = 20
SCREEN_HEIGHT_PIX = SCREEN_HEIGHT * CELL_SIZE

# MAZE GENERATION
ROOM_AMOUNT = 30
ROOM_EXTRA_SIZE = 3

FPS = 60
TARGET_CHECK_INTERVAL = 500
DEBUG_MODE = True

# Colors
COLOR_BACKGROUND = "black"
COLOR_PLAYER = "white"
COLOR_ENEMY = "red"
COLOR_HEALTH_BAR_BG = (255, 0, 0)
COLOR_HEALTH_BAR_FG = (0, 255, 0)
COLOR_HEALTH_BAR_BORDER = (255, 255, 255)
COLOR_WEAPON_BAR_BG = (50, 50, 50)
COLOR_WEAPON_BAR_FG = (200, 200, 200)

# Player Settings
PLAYER_SPEED = 5
PLAYER_SIZE = 1
PLAYER_MAX_HEALTH = 100
PLAYER_INVULNERABILITY_DURATION = 1000

# Weapons Settings
MAX_WEAPONS = 3

# Enemy Settings
ENEMY_SPEED = 0.5
ENEMY_HEALTH = 100
ENEMY_DAMAGE = 10

# UI Settings health bar
UI_HEALTH_BAR_WIDTH = 220
UI_HEALTH_BAR_HEIGHT = 22
UI_HEALTH_BAR_X = 20
UI_HEALTH_BAR_Y = 20

# UI Settings weapon display
UI_WEAPON_X = 20
UI_WEAPON_Y = UI_HEALTH_BAR_Y + UI_HEALTH_BAR_HEIGHT + 8
UI_WEAPON_BAR_X = 5
UI_WEAPON_BAR_Y = 5

# UI Settings


# Base directory of the project (src/)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Item Settings
GLOBAL_DROP_CHANCE = 0.3

from config.constants import RARITY_COMMON, RARITY_RARE, RARITY_LEGENDARY

RARITY_WEIGHTS = {RARITY_COMMON: 70, RARITY_RARE: 25, RARITY_LEGENDARY: 5}

RARITY_SCALING = {RARITY_COMMON: 1.0, RARITY_RARE: 1.5, RARITY_LEGENDARY: 3.0}

COLOR_RARITY = {
    RARITY_COMMON: (128, 128, 128),  # Grey
    RARITY_RARE: (0, 0, 255),  # Blue
    RARITY_LEGENDARY: (255, 165, 0),  # Orange
}
