import os

CELL_SIZE = 8
GRID_WIDTH = 100
GRID_HEIGHT = 100
SCREEN_WIDTH = GRID_WIDTH * CELL_SIZE
SCREEN_HEIGHT = GRID_HEIGHT * CELL_SIZE

MAX_WEAPONS = 3

FPS = 60
TARGET_CHECK_INTERVAL = 500
DEBUG_MODE = True

# Colors
COLOR_BACKGROUND = "black"
COLOR_PLAYER = (255, 255, 255)
COLOR_ENEMY = "red"
COLOR_HEALTH_BAR_BG = (255, 0, 0)
COLOR_HEALTH_BAR_FG = (0, 255, 0)
COLOR_HEALTH_BAR_BORDER = (255, 255, 255)

# Player Settings
PLAYER_SPEED = 5
PLAYER_SIZE = 1
PLAYER_MAX_HEALTH = 100
PLAYER_INVULNERABILITY_DURATION = 1000

# Enemy Settings
ENEMY_SPEED = 0.5
ENEMY_HEALTH = 100
ENEMY_DAMAGE = 10

# UI Settings
UI_HEALTH_BAR_WIDTH = 200
UI_HEALTH_BAR_HEIGHT = 20
UI_HEALTH_BAR_X = 10
UI_HEALTH_BAR_Y = 10

# Base directory of the project (src/)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Item Settings
GLOBAL_DROP_CHANCE = 0.3

from config.constants import RARITY_COMMON, RARITY_RARE, RARITY_LEGENDARY

RARITY_WEIGHTS = {
    RARITY_COMMON: 70,
    RARITY_RARE: 25,
    RARITY_LEGENDARY: 5
}

RARITY_SCALING = {
    RARITY_COMMON: 1.0,
    RARITY_RARE: 1.5,
    RARITY_LEGENDARY: 3.0
}

COLOR_RARITY = {
    RARITY_COMMON: (128, 128, 128),  # Grey
    RARITY_RARE: (0, 0, 255),        # Blue
    RARITY_LEGENDARY: (255, 165, 0)  # Orange
}
