import os

CELL_SIZE = 8
GRID_WIDTH = 100
GRID_HEIGHT = 100
SCREEN_WIDTH = GRID_WIDTH * CELL_SIZE
SCREEN_HEIGHT = GRID_HEIGHT * CELL_SIZE

MAX_WEAPONS = 3

FPS = 60
TARGET_CHECK_INTERVAL = 500
DEBUG_MODE = True

# Colors
COLOR_BACKGROUND = "black"
COLOR_PLAYER = (255, 255, 255)
COLOR_ENEMY = "red"
COLOR_HEALTH_BAR_BG = (255, 0, 0)
COLOR_HEALTH_BAR_FG = (0, 255, 0)
COLOR_HEALTH_BAR_BORDER = (255, 255, 255)
COLOR_WEAPON_BAR_BG = (50, 50, 50)
COLOR_WEAPON_BAR_FG = (200, 200, 200)

# Player Settings
PLAYER_SPEED = 5
PLAYER_SIZE = 1
PLAYER_MAX_HEALTH = 100
PLAYER_INVULNERABILITY_DURATION = 1000

# Enemy Settings
ENEMY_SPEED = 0.5
ENEMY_HEALTH = 100
ENEMY_DAMAGE = 10

# UI Settings health bar
UI_HEALTH_BAR_WIDTH  = 220
UI_HEALTH_BAR_HEIGHT = 22
UI_HEALTH_BAR_X      = 20
UI_HEALTH_BAR_Y      = 20

#UI Settings weapon display
UI_WEAPON_X = 20
UI_WEAPON_Y = UI_HEALTH_BAR_Y + UI_HEALTH_BAR_HEIGHT + 8
UI_WEAPON_BAR_X = 5
UI_WEAPON_BAR_Y = 5

# UI Settings 


# Base directory of the project (src/)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

